--------- INSERT ALBUMS ---------
INSERT INTO albums (title, release_year, cover_image) VALUES
 ('The Velvet Underground & Nico', 1967, 'albumCovers/vu_nico.jpg'),
   ('Loaded', 1970, 'albumCovers/loaded.jpg'),
   ('Transformer', 1972, 'albumCovers/transformer.jpg'),
   ('Berlin', 1973, 'albumCovers/berlin.jpg'),
   ('Hunky Dory', 1971, 'albumCovers/hunky_dory.jpg'),
   ('Ziggy Stardust', 1972, 'albumCovers/ziggy_stardust.jpg'),
   ('The Dark Side of the Moon', 1973, 'albumCovers/dark_side.jpg'),
   ('Wish You Were Here', 1975, 'albumCovers/wish_you_were_here.jpg'),
   ('Animals', 1977, 'albumCovers/animals.jpg'),
   ('Harvest', 1972, 'albumCovers/harvest.jpg'),
   ('After the Gold Rush', 1970, 'albumCovers/after_the_gold_rush.jpg'),
   ('Rumours', 1977, 'albumCovers/rumours.jpg'),
   ('Tapestry', 1971, 'albumCovers/tapestry.jpg'),
   ('Bridge Over Troubled Water', 1970, 'albumCovers/bridge_over_troubled_water.jpg'),
   ('Goodbye Yellow Brick Road', 1973, 'albumCovers/goodbye_ybr.jpg'),
   ('Blood on the Tracks', 1975, 'albumCovers/blood_on_the_tracks.jpg'),
   ('The Doors', 1967, 'albumCovers/the_doors.jpg'),
   ('Morrison Hotel', 1970, 'albumCovers/morrison_hotel.jpg'),
   ('Let It Bleed', 1969, 'albumCovers/let_it_bleed.jpg'),
   ('Sticky Fingers', 1971, 'albumCovers/sticky_fingers.jpg'),
   ('Tea for the Tillerman', 1970, 'albumCovers/tea_for_the_tillerman.jpg'),
   ('Blue', 1971, 'albumCovers/blue_joni.jpg'),
   ('Court and Spark', 1974, 'albumCovers/court_and_spark.jpg'),
   ('Paris 1919', 1973, 'albumCovers/paris_1919.jpg'),
   ('Songs of Leonard Cohen', 1967, 'albumCovers/songs_of_leonard_cohen.jpg'),
   ('The Queen Is Dead', 1986, 'albumCovers/the_queen_is_dead.jpg'),
   ('Strangeways, Here We Come', 1987, 'albumCovers/strangeways.jpg'),
   ('Louder Than Bombs', 1987, 'albumCovers/louder_than_bombs.jpg'),
   ('OK Computer', 1997, 'albumCovers/ok_computer.jpg'),
   ('Kid A', 2000, 'albumCovers/kid_a.jpg'),
   ('In Rainbows', 2007, 'albumCovers/in_rainbows.jpg'),
   ('The Bends', 1995, 'albumCovers/the_bends.jpg'),
   ('Fetch the Bolt Cutters', 2020, 'albumCovers/fetch_the_bolt_cutters.jpg'),
   ('When the Pawn...', 1999, 'albumCovers/when_the_pawn.jpg'),
   ('Extraordinary Machine', 2005, 'albumCovers/extraordinary_machine.jpg'),
   ('Grace', 1994, 'albumCovers/grace.jpg'),
   ('Either/Or', 1997, 'albumCovers/either_or.jpg'),
   ('XO', 1998, 'albumCovers/xo.jpg'),
   ('For Emma, Forever Ago', 2007, 'albumCovers/for_emma.jpg'),
   ('Carrie & Lowell', 2015, 'albumCovers/carrie_and_lowell.jpg'),
   ('Let It Be', 1984, 'albumCovers/let_it_be_replacements.jpg'),
   ('Tim', 1985, 'albumCovers/tim.jpg'),
   ('Marquee Moon', 1977, 'albumCovers/marquee_moon.jpg'),
   ('Unknown Pleasures', 1979, 'albumCovers/unknown_pleasures.jpg'),
   ('The Soft Bulletin', 1999, 'albumCovers/the_soft_bulletin.jpg'),
   ('The Glow Pt. 2', 2001, 'albumCovers/the_glow_pt2.jpg'),
   ('Pink Moon', 1972, 'albumCovers/pink_moon.jpg'),
   ('Dusty in Memphis', 1969, 'albumCovers/dusty_in_memphis.jpg'),
   ('Odessey and Oracle', 1968, 'albumCovers/odessey_and_oracle.jpg'),
   ('Forever Changes', 1967, 'albumCovers/forever_changes.jpg');

--------- INSERT ARTISTS ---------
